# client_config.yaml configuration

client:
  # Client identification
  id: "client_1"
  server_url: "http://localhost:8080"
  
  # Data configuration
  data:
    batch_size: 32
    shuffle_buffer: 1000
    prefetch_buffer: 10
    input_dim: 32
    dataset_size: 100

  # Model configuration
  model:
    type: "feedforward"
    hidden_dims: [128, 64]
    activation: "relu"

  # Training configuration
  training:
    local_epochs: 3
    learning_rate: 0.001
    batch_size: 32
    
  # Privacy configuration
  privacy:
    differential_privacy: false
    noise_multiplier: 0.1
    
monitoring:
  log_level: "INFO"
