client:
  id: "client_2"
  server_url: "http://localhost:8080"
  
  data:
    batch_size: 32
    shuffle_buffer: 1000
    prefetch_buffer: 10
    input_dim: 32
    dataset_size: 100

  model:
    type: "feedforward"
    hidden_dims: [128, 64]
    activation: "relu"

  training:
    local_epochs: 3
    learning_rate: 0.001
    
  privacy:
    differential_privacy: false
    noise_multiplier: 0.1
    
monitoring:
  log_level: "INFO"
