version: 1
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/federated_learning.log
loggers:
  '':  # Root logger
    level: INFO
    handlers: [console, file] 