# server.yaml configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server
  namespace: federated-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-server
  template:
    metadata:
      labels:
        app: fl-server
    spec:
      containers:
      - name: fl-server
        image: fl-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_PATH
          value: /app/config/server_config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: server-config

